### ISSUE TITLE
Reduce font family names defined by an font-face CSS at-rule

### ISSUE THREAD

**Issue by 7studio** [ben-eb/postcss-reduce-idents#4]
It could be interesting to go further by reducing font family name defined by an `@font-face` rule with a case-insensitive comparison. I thought about this feature when I looked at your other module [postcss-discard-unused](https://github.com/ben-eb/postcss-discard-unused) and its `fontFace` option.

**input**:
```css
@font-face {
  font-family: My CuStoM FoNt;
  src: local(Comic Sans MS);
}

body {
  font-family: My Custom Font;
}
```
**output**:
```css
@font-face {
  font-family: a;
  src: local(Comic Sans MS);
}

body {
  font-family: a;
}
```

Obviously, this feature should work correctly only if you use [postcss-minify-font-values](https://github.com/trysound/postcss-minify-font-values) before this module but it is the same behaviour in postcss-discard-unused.

If your are interested by this enhancement I will be happy to work on or help you to test it.
